//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_StringMap
    {
        public int StringMapId { get; set; }
        public string ObjectName { get; set; }
        public string AttributeName { get; set; }
        public Nullable<int> AttributeValue { get; set; }
        public string Value { get; set; }
    }
}
