//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TR_TargetSetting
    {
        public int TargetId { get; set; }
        public string TargetName { get; set; }
        public Nullable<System.DateTime> TargetFrom { get; set; }
        public Nullable<System.DateTime> TargetTo { get; set; }
        public Nullable<int> TargetData { get; set; }
        public Nullable<decimal> TargetAmount { get; set; }
        public Nullable<int> Advance { get; set; }
        public Nullable<int> Intermediate { get; set; }
        public Nullable<int> Beginner { get; set; }
        public Nullable<int> CustProId { get; set; }
        public string Created_by { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
