//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_CustomerProject
    {
        public int CustProId { get; set; }
        public string CustProName { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> CustProExpired { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public string Param4 { get; set; }
        public string Param5 { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> r_closing { get; set; }
        public Nullable<int> r_promise { get; set; }
        public Nullable<int> r_prospect { get; set; }
        public Nullable<int> r_contact { get; set; }
        public Nullable<int> r_connect { get; set; }
        public Nullable<int> r_not_connect { get; set; }
    }
}
