//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TT_CallHistory
    {
        public int CallLogId { get; set; }
        public string CallDuration { get; set; }
        public string CallStatus { get; set; }
        public string SubStatus { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> CallDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ContactId { get; set; }
    }
}
